routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function() {
    Route::resource('companies', 'CompaniesController');
    
    Route::get('projects/create/{company_id?}', 'ProjectsController@create');
    Route::resource('projects', 'ProjectsController');
    
    Route::resource('roles', 'RolesController');
    Route::resource('tasks', 'TasksController');
    Route::resource('users', 'UsersController');
    Route::resource('comments', 'CommentsController');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    //
    protected $fillable = [
        'name',
        'description',
        'company_id',
        'user_id',
        'days'
    ];
    
    public function user()
    {
        return $this->belongsToMany('App\User');
    }
    
    public function company()
    {
        return $this->belongsTo('App\Company');
    }
    
    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use App\ProjectUser;
use App\Company;
use App\Comment;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use Illuminate\Support\Facades\DB;


class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        DB::enableQueryLog();
        //
        if(Auth::check()) {
            $projects = Project::where('projects.user_id', Auth::user()->id)->get();
//            $company = Company::where('projects.company_id', 'company.id')->get();
//            dd($projects);
            
            return view('projects.index', ['projects' => $projects]);
        }
        
        return view('auth.login');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create( $company_id = null )
    {
        //
//        $companies = null;
//       if(!$company_id) {
            $companies = Company::where('user_id', Auth::user()->id)->get();
//        }
        
        return view('projects.create', ['company_id'=> $company_id, 'companies'=> $companies]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if(Auth::check()) {
            $project = Project::create([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
                'company_id' => $request->input('company_id'),
                'user_id' => Auth::user()->id,
                'days' => $request->input('days')
            ]);
            
            if($project) {
                return redirect()->route('projects.show', ['project' => $project->id])->with('success', $project->name.' has been created successfully.'.$request->input('company_id'));
            }
        }
        
        return back()->withInput()->with('errors', 'Error creating new project');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        //
        $project = Project::find($project->id);
        $comments = $project->comments;
        $company = $project->company;
        dd($project);
        
        return view('projects.show', ['project'=> $project, 'comments'=> $comments, 'company'=> $company]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        //
        $project = Project::find($project->id);
        $company = Company::find($project->company_id);
        
        return view('projects.edit', ['project'=> $project, 'company'=> $company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        //
        $projectUpdated = Project::where('id', $project->id)->update([
                                                                      'name' => $request->input('name'),
                                                                      'description' => $request->input('description'),
                                                                      'days' => $request->input('days')
                                                                      ]);
        
        if($projectUpdated) {
            return redirect()->route('projects.show', ['project'=> $project->id])->with('success', $project->name. ' was updated successfully.');
        }
        
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
        $project = Project::find($project->id);
        if($project->delete()) {
            return redirect()->route('projects.index')->with('success', $project->name.' was removed successfully.');
        }
        
        return back()->withInput()->with('errors', $project->name.' could not be deleted!');
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
<div class="col-lg-9 col-md-9 col-sm-9 pull-left">
    <h4>Create a new Project</h4>
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12">
            <form method="post" action="{{ route('projects.store') }}">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="project-name">Name<span class="required">*</span></label>
                    <input placeholder="Enter Name" id="project-name" required name="name" spellcheck="false" class="form-control" />
                </div>
                
                <div class="form_group">
                    <label for="company-id">Company<span class="required">*</span></label>
                    <select id="company-id" name="company_id" class="form-control" required>
                        <option value="">Select a Company</option>
                    @foreach($companies as $company)
                        @if ($company->id == $company_id) 
                        <option value="{{ $company->id }}" selected>{{ $company->name }}</option>
                        @else
                        <option value="{{ $company->id }}">{{ $company->name }} {{ $company->id }}</option>
                        @endif
                    @endforeach
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="project-description">Description</label>
                    <textarea placeholder="Enter Description" id="project-description" name="description" rows="5" spellcheck="false" class="form-control autosize-target text-left">
                    </textarea>
                </div>
                
                <div class="form-group">
                    <label for="project-days">Days</label>
                    <input placeholder="Time to complete" id="project-days" required name="days" spellcheck="false" class="form-control" />
                </div>
                    
                <div class="form-group"><input type="submit" class="btn btn-primary" value="Submit" /></div>
            </form>
        </div>
    </div>
    <hr>
</div>

<aside class="col-lg-3 col-md-3 col-sm-3 blog-sidebar pull-right">
    <div class="sidebar-module">
        <h4>View</h4>
        <ol class="list-unstyled">
            <li><a href="/projects/"><i class="fas fa-briefcase"></i> My Projects</a></li>
        </ol>
    </div>

    <!--
    <div class="sidebar-module">
        <h4>Members</h4>
        <ol class="list-unstyled">
            <li><a href=""></a></li>
        </ol>
    </div>
    -->
</aside>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="col-lg-9 col-md-9 col-sm-9 pull-left">
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12">
            <h4>Edit Project</h4>
            <form method="post" action="{{ route('projects.update', [$project->id]) }}">
                @csrf
                <input type="hidden" name="_method" value="put" />
                <div class="form-group">
                    <label for="project-name">Name<span class="required">*</span></label>
                    <input placeholder="Enter Name" id="project-name" required name="name" spellcheck="false" class="form-control" value="{{ $project->name }}" />
                </div>
                
                <div class="form-group">
                    <label for="company-name">Company</label>
                    <input disabled id="company-name" name="company-name" spellcheck="false" class="form-control" value="{{ $company->name }}" />
                </div>
                
                <div class="form-group">
                    <label for="project-description">Description</label>
                    <textarea placeholder="Enter Description" id="project-description" name="description" rows="5" spellcheck="false" class="form-control autosize-target text-left">
                        {{ $project->description }}
                    </textarea>
                </div>
                
                <div class="form-group">
                    <label for="project-days">Days</label>
                    <input placeholder="Time to complete" id="project-days" required name="days" spellcheck="false" class="form-control" value="{{ $project->days }}" />
                </div>
                    
                <div class="form-group"><input type="submit" class="btn btn-primary" value="Submit" /></div>
            </form>
        </div>
    </div>
    <hr>
</div>

<aside class="col-lg-3 col-md-3 col-sm-3 blog-sidebar pull-right">
    <div class="sidebar-module">
        <h4>View</h4>
        <ol class="list-unstyled">
          <li><a href="/projects/{{ $project->id }}/"><i class="fas fa-thumbtack"></i> {{ $project->name }}</li>
          <li><a href="/projects/"><i class="fas fa-briefcase"></i> All Projects</a></li>
        </ol>
    </div>

    <!--
    <div class="sidebar-module">
        <h4>Members</h4>
        <ol class="list-unstyled">
            <li><a href=""></a></li>
        </ol>
    </div>
    -->
</aside>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-12 col-lg-12">
    <div class="card">
        <div class="card-header bg-primary text-white"><h4>Projects</h4></div>
        <div class="card-body">
            <div class="row mb-3">
                <div class="col-12 themed-grid-col"><a href="/projects/create/" class="float-right btn btn-primary btn-sm">Add a Project</a></div>
                <div class="col-4">Project</div>
                <div class="col-4">Company</div>
                <div class="col-4">Days</div>
            @foreach($projects as $project)
                <div class="col-4 themed-grid-col"><a href="/projects/{{ $project->id }}">{{ $project->name }}</a></div>
                <div class="col-4 themed-grid-col">{{--<a href="/companies/{{ $company->id }}">{{ $company->name }}</a>--}}</div>
                <div class="col-4 themed-grid-col">{{ $project->days }}</div>
            @endforeach
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')
<div class="col-lg-9 col-md-9 col-sm-9 pull-left">
    <div class="jumbotron">
        <h1 class="display-3">{{ $project->name }}</h1>
        <p>Project for: {{ $company->name }}</p>
        <p>Time to complete: {{ $project->days }} days.</p>
        <p>{{ $project->description }}</p>
        <!-- <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p> -->
    </div>
        
    <!-- Comments -->
    @include('partials.comments');
    
    <div class="row container-fluid">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <form method="post" action="{{ route('comments.store') }}">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="comment-body">Comment</label>
                    <textarea placeholder="Enter Comments" id="comment-body" name="body" rows="3" spellcheck="false" class="form-control autosize-target text-left">
                    </textarea>
                </div>
                    
                <div class="form-group">
                    <label for="comment-url">URL to work done</label>
                    <input placeholder="Enter URL" id="comment-url" required name="url" spellcheck="false" class="form-control" />
                </div>
                    
                <input type="hidden" name="commentable_id" value="{{ $project->id }}" />
                <input type="hidden" name="commentable_type" value="App\Project" />
                <div class="form-group"><input type="submit" class="btn btn-primary" value="Submit" /></div>
            </form>
        </div>
    </div>
</div>
        
<aside class="col-lg-3 col-md-3 col-sm-3 pull-right">
    <div class="sidebar-module">
        @include('partials.view-nav')
        <h4>Actions</h4>
        <ol class="list-unstyled">
            <li><a href="/projects/{{ $project->id }}/edit/"><i class="fas fa-edit"></i> Edit {{ $project->name }}</a></li>
            <br />
            @if($project->user_id == Auth::user()->id)
            <li><a href="#" onclick="
                                    var result = confirm('Are you sure you wish to delete {{ $project->name }}?');
                                    if(result) {
                                        event.preventDefault();
                                        document.getElementById('delete-form').submit();
                                    }
                                    ">
                    <i class="fas fa-trash-alt"></i> Delete {{ $project->name }} Task
                </a>
                <form id="delete-form" action="{{ route('projects.destroy', [$project->id]) }}" method="POST" style="display: none;">
                    <input type="hidden" name="_method" value="delete" />
                    {{ csrf_field() }}
                </form>
            </li>
            @endif
        </ol>
        
        <h4>Team Members</h4>
        <ul class="list-unstyled" id="member-list">
            @foreach($project->users as $user)
            <li><a href="#">{{ $user->name }}</a></li>
            @endforeach
        </ul>
    </div>
        
    <!--
    <div class="sidebar-module">
        <h4>Members</h4>
        <ol class="list-unstyled">
            <li><a href=""></a></li>
        </ol>
    </div>
    -->
</aside>
<hr>
@endsection