routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function() {
    Route::resource('companies', 'CompaniesController');
    
    Route::get('projects/create/{company_id?}', 'ProjectsController@create');
    Route::resource('projects', 'ProjectsController');
    
    Route::resource('roles', 'RolesController');
    Route::resource('tasks', 'TasksController');
    Route::resource('users', 'UsersController');
    Route::resource('comments', 'CommentsController');
});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    //
    protected $fillable = [
        'name',
        'description',
        'user_id'
    ];
    
    public function user()
    {
        return $this->belongsTo('App\User');
    }
    
    public function projects()
    {
        return $this->hasMany('App\Project');
    }
    
    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if(Auth::user()->id == 1) {
            $companies = Company::all();
            
            return view('companies.index', ['companies'=> $companies]);
        }
        elseif(Auth::check()) {
            $companies = Company::where('user_id', Auth::user()->id)->get();
            
            return view('companies.index', ['companies'=> $companies]);
        }
        
        return view('auth.login');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if(Auth::check()) {
            $company = Company::create([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
                'user_id' => Auth::user()->id
            ]);
        
            if($company) {
                return redirect()->route('companies.show', ['company'=>$company->id])->with('success', $company->name.' was created successfully.');
            }
        }
        
        return back()->withInput()->with('errors', 'Error creating a new company.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //create query for which company to display and return the view needed
        //$company = Company::where('id', $company->id)->first();
        
        if((Auth::user()->id == $company->user_id) || (Auth::user()->id == 1)) {
            $company = Company::find($company->id);
            return view('companies.show', ['company'=> $company]);
        }
        
        return redirect()->route('companies.index')->with('error', 'Error retrieving company.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        //
        $company = company::find($company->id);
        return view('companies.edit', ['company'=>$company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company)
    {
        //
        $companyUpdate = Company::where('id', $company->id)
                                    ->update([
                                              'name'=>$request->input("name"),
                                              'description'=>$request->input("description")
                                             ]);
        if($companyUpdate) {
            return redirect()->route('companies.show', ['company' => $company->id])->with('success', $company->name.' was updated successfully.');
        }
        
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        //
        $company = company::find($company->id);
        if($company->delete()) {
            return redirect()->route('companies.index')->with('success', $company->name.' was deleted successfully.');
        }
        
        return back()->withInput()->with('error', $company->name.' could not be deleted!');
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')

@section('content')
<div class="col-lg-9 col-md-9 col-sm-9 pull-left">
    <h4>Create a new Company</h4>
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12">
            <form method="post" action="{{ route('companies.store') }}">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="company-name">Name<span class="required">*</span></label>
                    <input placeholder="Enter Name" id="company-name" required name="name" spellcheck="false" class="form-control" />
                </div>
                
                <div class="form-group">
                    <label for="company-description">Description</label>
                    <textarea placeholder="Enter Description" id="company-description" name="description" rows="5" spellcheck="false" class="form-control autosize-target text-left">
                    </textarea>
                </div>
                
                <div class="form-group"><input type="submit" class="btn btn-primary" value="Submit" /></div>
            </form>
        </div>
    </div>
    <hr>
</div>

<aside class="col-lg-3 col-md-3 col-sm-3 blog-sidebar pull-right">
    <div class="sidebar-module">
        <h4>Actions</h4>
        <ol class="list-unstyled">
            <li><a href="/companies/">My Companies</a></li>
        </ol>
    </div>

    <!--
    <div class="sidebar-module">
        <h4>Members</h4>
        <ol class="list-unstyled">
            <li><a href=""></a></li>
        </ol>
    </div>
    -->
</aside>
@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="col-lg-9 col-md-9 col-sm-9 pull-left">
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12">
            <form method="post" action="{{ route('companies.update', [$company->id]) }}">
                @csrf
                <input type="hidden" name="_method" value="put" />
                <div class="form-group">
                    <label for="company-name">Name<span class="required">*</span></label>
                    <input placeholder="Enter Name" id="company-name" required name="name" spellcheck="false" class="form-control" value="{{ $company->name }}" />
                </div>
                
                <div class="form-group">
                    <label for="company-description">Description</label>
                    <textarea placeholder="Enter Description" id="company-description" name="description" rows="5" spellcheck="false" class="form-control autosize-target text-left">
                        {{ $company->description }}
                    </textarea>
                </div>
                
                <div class="form-group"><input type="submit" class="btn btn-primary" value="Submit" /></div>
            </form>
        </div>
    </div>
    <hr>
</div>

<aside class="col-lg-3 col-md-3 col-sm-3 blog-sidebar pull-right">
    <div class="sidebar-module">
        <h4 class="font-italic">Actions</h4>
        <ol class="list-unstyled">
          <li><a href="/companies/{{ $company->id }}/">{{ $company->name }}</li>
          <li><a href="/companies/">My Companies</a></li>
        </ol>
    </div>

    <!--
    <div class="sidebar-module">
        <h4>Members</h4>
        <ol class="list-unstyled">
            <li><a href=""></a></li>
        </ol>
    </div>
    -->
</aside>
@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-12 col-lg-12">
    <div class="card">
        <div class="card-header bg-primary text-white"><h4>Companies</h4></div>
        <div class="card-body">
            <ul class="list-group">
                <li class="list-group-flush list-group-item"><a href="/companies/create/" class="float-right btn btn-primary btn-sm">Add a Company</a></li>
            @foreach($companies as $company)
                <li class="list-group-item"><a href="/companies/{{ $company->id }}">{{ $company->name }}</a></li>
            @endforeach
            </ul>
        </div>
    </div>
</div>
@endsection

resources/views/companies/show.blade.php
@extends('layouts.app')

@section('content')
<div class="col-lg-9 col-md-9 col-sm-9 pull-left">
    <div class="jumbotron">
        <h1 class="display-3">{{ $company->name }}</h1>
        <p>{{ $company->description }}</p>
        <!-- <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p> -->
    </div>

    <!-- Example row of columns -->
    <div class="row col-lg-12 col-md-12 col-sm-12">
        <a href="/projects/create/{{ $company->id }}" class="float-right btn btn-primary btn-sm">Add Project</a>
    </div>
        
    <div class="row col-lg-12 col-md-12 col-sm-12">
    @foreach($company->projects as $project)
        <div class="col-lg-4 col-md-4 col-sm-4">
            <h2>{{ $project->name }}</h2>
            <p>{{ $project->description }}</p>
            <p><a class="btn btn-secondary" href="/projects/{{ $project->id }}" role="button">View Project »</a></p>
        </div>
    @endforeach
    </div>
</div>
        
<aside class="col-lg-3 col-md-3 col-sm-3 pull-right">
    <div class="sidebar-module">
        <h4>Actions</h4>
        <ol class="list-unstyled">
            <li><a href="/companies/">My Companies</a></li>
            <br />
            <li><a href="/companies/{{ $company->id }}/edit/">Edit {{ $company->name }}</a></li>
            <li><a href="/projects/create/{{ $company->id }}">Add Project</a></li>
            <br />
            <li><a href="#" onclick="
                                    var result = confirm('Are you sure you wish to delete {{ $company->name }}?');
                                    if(result) {
                                        event.preventDefault();
                                        document.getElementById('delete-form').submit();
                                    }
                                    ">
                    Delete {{ $company->name }}
                </a>
                <form id="delete-form" action="{{ route('companies.destroy', [$company->id]) }}" method="POST" style="display: none;">
                    <input type="hidden" name="_method" value="delete" />
                    {{ csrf_field() }}
                </form>
            </li>
        </ol>
    </div>
        
    <!--
    <div class="sidebar-module">
        <h4>Members</h4>
        <ol class="list-unstyled">
            <li><a href=""></a></li>
        </ol>
    </div>
    -->
</aside>
<hr>
@endsection