routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function() {
    Route::resource('companies', 'CompaniesController');
    
    Route::get('projects/create/{company_id?}', 'ProjectsController@create');
    Route::resource('projects', 'ProjectsController');
    
    Route::resource('roles', 'RolesController');
    Route::resource('tasks', 'TasksController');
    Route::resource('users', 'UsersController');
    Route::resource('comments', 'CommentsController');
});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    //
    protected $fillable = [
        'name'
    ];
    
    public function users() {
        return $this->hasMany('App\User');
    }
}

app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


class RolesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if(Auth::check()) {
            $roles = Role::all();
            
            return view('roles.index', ['roles'=> $roles]);
        }
        
        return view('auth.login');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if(Auth::check()) {
            $role = Role::create(['name'=> $request->input('name')]);
            
            if($role) {
                return redirect()->route('roles.show', ['role'=> $role->id])->with('success', $role->name.' role was created successfully.');
           }
        }
        
        return back()->withInput()->with('error', 'The new role '.$role->name.' was not created');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //
        $role = Role::find($role->id);
        
        return view('roles.show', ['role'=> $role]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        //
        $role = Role::find($role->id);
        
        view('role.edit', ['role'=> $role]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        //
        $roleUpdated = Role::where('id', $role->id)->update(['name'=> $request->input('name')]);
        
        if($roleUpdated) {
            return redirect()->route('routes.show', ['role'=> $role->id])->with('success', $role->name.' was updated successfully.');
        }
        
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        //
        $role = Role::find($role->id);
        if($role->delete()) {
            return redirect()->route('role.index')->with('success', 'The '.$role-name.' was removed successfully.');
        }
        
        return back()->withInput()->with('error', $role-name.' could not be deleted.');
    }
}

resources/views/roles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="col-lg-9 col-md-9 col-sm-9 pull-left">
    <h4>Create a new Role</h4>
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12">
            <form method="post" action="{{ route('roles.store') }}">
                @csrf
                <div class="form-group">
                    <label for="role-name">Name<span class="required">*</span></label>
                    <input placeholder="Enter Name" id="role-name" required name="name" spellcheck="false" class="form-control" />
                </div>
                
                <div class="form-group"><input type="submit" class="btn btn-primary" value="Submit" /></div>
            </form>
        </div>
    </div>
    <hr>
</div>

<aside class="col-lg-3 col-md-3 col-sm-3 blog-sidebar pull-right">
    <div class="sidebar-module">
        @include('partials.view-nav');
    </div>
</aside>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="col-lg-9 col-md-9 col-sm-9 pull-left">
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12">
            <form method="post" action="{{ route('route.update', [$route->id]) }}">
                @csrf
                <input type="hidden" name="_method" value="put" />
                <div class="form-group">
                    <label for="company-name">Name<span class="required">*</span></label>
                    <input placeholder="Enter Name" id="role-name" required name="name" spellcheck="false" class="form-control" value="{{ $role->name }}" />
                </div>
                
                <div class="form-group"><input type="submit" class="btn btn-primary" value="Submit" /></div>
            </form>
        </div>
    </div>
    <hr>
</div>

<aside class="col-lg-3 col-md-3 col-sm-3 blog-sidebar pull-right">
    <div class="sidebar-module">
        @include('partials.view-nav');
    </div>
</aside>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-12 col-lg-12">
    <div class="card">
        <div class="card-header bg-primary text-white"><h4>Roles</h4></div>
        <div class="card-body">
            <ul class="list-group">
                <li class="list-group-flush list-group-item"><a href="/roles/create/" class="float-right btn btn-primary btn-sm">Add a Role</a></li>
            @foreach($roles as $role)
                <li class="list-group-item"><a href="/roles/{{ $role->id }}">{{ $role->name }}</a></li>
            @endforeach
            </ul>
        </div>
    </div>
</div>
@endsection

resources/views/roles/show.blade.php
@extends('layouts.app')

@section('content')
<div class="col-lg-9 col-md-9 col-sm-9 pull-left">
    <div class="jumbotron">
        <h1 class="display-3">{{ $role->name }}</h1>
    </div>

    <!-- Example row of columns -->
    <div class="row col-lg-12 col-md-12 col-sm-12">
        <a href="/roles/create/{{ $role->id }}" class="float-right btn btn-primary btn-sm">Add Role</a>
    </div>
</div>
        
<aside class="col-lg-3 col-md-3 col-sm-3 pull-right">
    <div class="sidebar-module">
        @include('partials.view-nav')
        
        <h4>Actions</h4>
        <ol class="list-unstyled">
            <li><a href="/roles/{{ $role->id }}/edit/">Edit {{ $role->name }}</a></li>
            <li><a href="#" onclick="
                                    var result = confirm('Are you sure you wish to delete {{ $role->name }}?');
                                    if(result) {
                                        event.preventDefault();
                                        document.getElementById('delete-form').submit();
                                    }
                                    ">
                    Delete {{ $role->name }}
                </a>
                <form id="delete-form" action="{{ route('roles.destroy', [$role->id]) }}" method="POST" style="display: none;">
                    @csrf_field
                    <input type="hidden" name="_method" value="delete" />
                </form>
            </li>
        </ol>
    </div>
</aside>
<hr>
@endsection